#! /usr/bin/env python3

import time
import os
import sys

time.sleep(int(os.getenv("DELAY", "0")))

jobsperuser = """\
job1
job2
"""

if "-u" in sys.argv and len(sys.argv) >= 3:
    print(jobsperuser)
    sys.exit(0)

sys.exit(1)