#! /usr/bin/env python3

import time
import os
import sys

JOBNAME = "testjob1"

time.sleep(int(os.getenv("DELAY", "0")))

if len(sys.argv)  > 1:
    print(JOBNAME)
    sys.exit(0)

sys.exit(1)