#! /usr/bin/env python3

import time
import os
import sys

time.sleep(int(os.getenv("DELAY", "0")))

if len(sys.argv) == 2:
    # delete by id
    sys.exit(0)
elif len(sys.argv) == 3 and sys.argv[1] == "-u":
    # delete by user
    sys.exit(0)

sys.exit(1)